# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4UbIVXZBGc18FCi2DWW5u2KkZrYpZHi
"""

import pandas as pd
# all current sentences
zh_current = pd.read_csv('Chinese_current_pages', sep = '\t', names = ['sentence', 'id'])
bg_current = pd.read_csv('Bulgarian_current_pages', sep = '\t', names = ['sentence', 'id'])
# the map of qid and pid
zh_map = pd.read_csv('/wiki_pid_qid_map/chineseMap.csv')
bg_map = pd.read_csv('/wiki_pid_qid_map/bulgarianMap.csv')
zh_map_dict = pd.Series(zh_map.Q_id.values,index=zh_map.page_id).to_dict()
bg_map_dict = pd.Series(bg_map.Q_id.values,index=bg_map.page_id).to_dict()

zh_qid = [zh_map_dict.get(i,'empty') for i in zh_current['id'].values]
bg_qid = [bg_map_dict.get(i,'empty') for i in bg_current['id'].values]

zh_current['qid'] = zh_qid
bg_current['qid'] = bg_qid

zh_current = zh_current.drop(zh_current[zh_current['qid'] == 'empty'].index)
bg_current = bg_current.drop(bg_current[bg_current['qid'] == 'empty'].index)

zh_id = set(zh_current['qid'].values)
bg_id = set(bg_current['qid'].values)

zh_drop_list = [n for n,i in enumerate(zh_current['qid'].values) if i not in bg_id]
bg_drop_list = [n for n,i in enumerate(bg_current['qid'].values) if i not in zh_id]

application_zh = zh_current.drop(zh_current.index[zh_drop_list])
application_bg = bg_current.drop(bg_current.index[bg_drop_list])

application_zh

application_bg

set(application_zh.qid) == set(application_bg.qid)